select * from Aluno
select * from curso
select * from disciplina
select * from disciplina_turma_professor
select * from grau_parentesco
select * from Professor
select * from Responsavel
select * from tbnotas
select * from turmas