//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaSENAI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aluno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aluno()
        {
            this.tbnotas = new HashSet<tbnotas>();
        }
    
        public int idAluno { get; set; }
        public int Responsavel_idResponsavel { get; set; }
        public int turmas_id_turmas { get; set; }
        public string nome { get; set; }
        public string sobrenome { get; set; }
        public string email { get; set; }
        public string telefone { get; set; }
        public Nullable<int> turma { get; set; }
        public string cpf { get; set; }
        public string senha { get; set; }
    
        public virtual Responsavel Responsavel { get; set; }
        public virtual turmas turmas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbnotas> tbnotas { get; set; }
    }
}
