//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaSENAI
{
    using System;
    using System.Collections.Generic;
    
    public partial class disciplina_turma_professor
    {
        public int id_DTP { get; set; }
        public int Professor_idProfessor { get; set; }
        public int disciplina_id_disciplina { get; set; }
        public int turmas_id_turmas { get; set; }
    
        public virtual disciplina disciplina { get; set; }
        public virtual Professor Professor { get; set; }
        public virtual turmas turmas { get; set; }
    }
}
