//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaSENAI
{
    using System;
    using System.Collections.Generic;
    
    public partial class disciplina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public disciplina()
        {
            this.disciplina_turma_professor = new HashSet<disciplina_turma_professor>();
        }
    
        public int id_disciplina { get; set; }
        public int notas_id_notas { get; set; }
        public string nome { get; set; }
        public Nullable<int> carga_horaria { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<disciplina_turma_professor> disciplina_turma_professor { get; set; }
        public virtual tbnotas tbnotas { get; set; }
    }
}
