//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaSENAI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bdsistemaescolaEntities : DbContext
    {
        public bdsistemaescolaEntities()
            : base("name=bdsistemaescolaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aluno> Aluno { get; set; }
        public virtual DbSet<curso> curso { get; set; }
        public virtual DbSet<disciplina> disciplina { get; set; }
        public virtual DbSet<disciplina_turma_professor> disciplina_turma_professor { get; set; }
        public virtual DbSet<grau_parentesco> grau_parentesco { get; set; }
        public virtual DbSet<Professor> Professor { get; set; }
        public virtual DbSet<Responsavel> Responsavel { get; set; }
        public virtual DbSet<tbnotas> tbnotas { get; set; }
        public virtual DbSet<turmas> turmas { get; set; }
    }
}
